import { useEffect, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowLeft, Loader2, Pencil, Plus, Save, Trash2, Wrench, X } from 'lucide-react';
import { createForgeMachineProfile, deleteForgeMachineProfile, getForgeMachineProfiles, updateForgeMachineProfile } from '../api/api';
import type { ForgeMachineProfile, ForgeMachineProfileInput } from '../api/api';
import ConfirmDialog from './ConfirmDialog';

const SAND = '#e8c58a'; const TEXT = '#f2ece0'; const DIM = 'rgba(242,236,226,0.48)'; const BORDER = 'rgba(232,197,138,0.11)';
const blank = (): ForgeMachineProfileInput => ({ name: '', model: '', notes: '' });
export default function ForgeMachineProfilesPage() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const returnTo = params.get('returnTo') || '/forge/exercises';
  const [profiles, setProfiles] = useState<ForgeMachineProfile[]>([]); const [editingId, setEditingId] = useState<string | null>(null); const [draft, setDraft] = useState<ForgeMachineProfileInput | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [pendingDelete, setPendingDelete] = useState<ForgeMachineProfile | null>(null);
  useEffect(() => { getForgeMachineProfiles().then(setProfiles).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Maschinenprofile konnten nicht geladen werden.')).finally(() => setLoading(false)); }, []);
  const edit = (profile?: ForgeMachineProfile) => { setEditingId(profile?.id ?? null); setDraft(profile ? { name: profile.name, model: profile.model, notes: profile.notes } : blank()); setError(null); };
  const save = async () => { if (!draft?.name.trim()) { setError('Gib dem Profil einen Namen.'); return; } setSaving(true); setError(null); try { const saved = editingId ? await updateForgeMachineProfile(editingId, draft) : await createForgeMachineProfile(draft); setProfiles((current) => [...current.filter((item) => item.id !== saved.id), saved].sort((a, b) => a.name.localeCompare(b.name))); setDraft(null); setEditingId(null); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : 'Profil konnte nicht gespeichert werden.'); } finally { setSaving(false); } };
  const remove = async () => { if (!pendingDelete) return; setSaving(true); setError(null); try { await deleteForgeMachineProfile(pendingDelete.id); setProfiles((current) => current.filter((item) => item.id !== pendingDelete.id)); setPendingDelete(null); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : 'Profil wird noch verwendet und kann nicht gelöscht werden.'); setPendingDelete(null); } finally { setSaving(false); } };
  if (loading) return <div className="flex justify-center py-24"><Loader2 className="animate-spin" style={{ color: SAND }} /></div>;
  return <div className="space-y-4 forge-anim"><header className="flex items-start gap-3"><button onClick={() => navigate(returnTo)} className="tap mt-1 flex h-9 w-9 items-center justify-center rounded-full" aria-label="Zurück zur Übungsbibliothek" style={{ color: SAND, background: 'rgba(232,197,138,0.08)' }}><ArrowLeft size={18} /></button><div className="min-w-0 flex-1"><p className="text-[10px] uppercase tracking-[0.18em]" style={{ color: SAND }}>Zentrale Verwaltung</p><h1 className="mt-1 text-[25px] font-semibold" style={{ color: TEXT }}>Maschinenprofile</h1><p className="mt-1 text-[11px]" style={{ color: DIM }}>Einmal anlegen, mehreren Übungen zuweisen.</p></div><button onClick={() => edit()} className="tap flex h-9 w-9 items-center justify-center rounded-full" style={{ color: SAND, border: `1px solid ${BORDER}` }} aria-label="Maschinenprofil anlegen"><Plus size={17} /></button></header>
    {error && <div className="rounded-2xl px-4 py-3 text-[12px]" style={{ color: '#fca5a5', background: 'rgba(248,113,113,0.1)' }}>{error}</div>}
    {draft && <section className="card-forge space-y-3 p-4" style={{ borderColor: `${SAND}44` }}><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.16em]" style={{ color: SAND }}>{editingId ? 'Profil bearbeiten' : 'Neues Profil'}</p><h2 className="mt-1 text-[15px] font-semibold" style={{ color: TEXT }}>Maschine beschreiben</h2></div><button onClick={() => setDraft(null)} className="tap p-1" style={{ color: DIM }}><X size={16} /></button></div><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="input-forge w-full" placeholder="Name, z. B. Studio Leg Press" /><input value={draft.model ?? ''} onChange={(event) => setDraft({ ...draft, model: event.target.value })} className="input-forge w-full" placeholder="Hersteller / Modell" /><textarea value={draft.notes ?? ''} onChange={(event) => setDraft({ ...draft, notes: event.target.value })} className="input-forge w-full resize-none text-[12px]" rows={3} placeholder="Gewichtsstufen / Notizen, z. B. 5, 12, 19, 26 kg" /><button onClick={() => void save()} disabled={saving} className="btn-forge flex w-full items-center justify-center gap-2">{saving ? <Loader2 size={15} className="animate-spin" /> : <Save size={15} />}Profil speichern</button></section>}
    <section className="space-y-2">{profiles.map((profile) => <article key={profile.id} className="card-forge flex items-start gap-3 p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl" style={{ color: SAND, background: 'rgba(232,197,138,0.1)' }}><Wrench size={18} /></div><div className="min-w-0 flex-1"><h2 className="text-[14px] font-medium" style={{ color: TEXT }}>{profile.name}</h2><p className="mt-0.5 text-[10px]" style={{ color: DIM }}>{profile.model || 'Kein Modell hinterlegt'}</p>{profile.notes && <p className="mt-2 whitespace-pre-wrap text-[11px] leading-relaxed" style={{ color: DIM }}>{profile.notes}</p>}</div><button onClick={() => edit(profile)} className="tap p-1" style={{ color: SAND }} aria-label={`${profile.name} bearbeiten`}><Pencil size={15} /></button><button onClick={() => setPendingDelete(profile)} className="tap p-1" style={{ color: DIM }} aria-label={`${profile.name} löschen`}><Trash2 size={15} /></button></article>)}{!profiles.length && !draft && <button onClick={() => edit()} className="w-full rounded-2xl border border-dashed p-7 text-center" style={{ borderColor: `${SAND}44`, color: SAND }}><Plus size={20} className="mx-auto" /><span className="mt-2 block text-[12px]">Erstes Maschinenprofil anlegen</span></button>}</section>
    <ConfirmDialog open={Boolean(pendingDelete)} busy={saving} destructive title="Maschinenprofil löschen?" description={pendingDelete ? `„${pendingDelete.name}“ wird entfernt. Wird es noch von Übungen genutzt, verhindert Forge das Löschen.` : ''} confirmLabel="Profil löschen" onCancel={() => setPendingDelete(null)} onConfirm={() => void remove()} />
  </div>;
}
