import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ChevronRight, Dumbbell, History, Loader2, Pencil, Plus, Search, Settings2, Trash2 } from 'lucide-react';
import { deleteForgeExercise, getForgeExercises } from '../api/api';
import type { ForgeExercise } from '../api/api';
import ConfirmDialog from './ConfirmDialog';

const SAND = '#e8c58a'; const TEXT = '#f2ece0'; const DIM = 'rgba(242,236,226,0.48)';
const equipmentLabel: Record<string, string> = { none: 'Ohne Equipment', barbell: 'Langhantel', dumbbell: 'Kurzhantel', kettlebell: 'Kettlebell', cable: 'Kabelzug', machine: 'Maschine', other: 'Sonstiges' };

export default function ForgeExerciseLibraryPage() {
  const navigate = useNavigate();
  const [exercises, setExercises] = useState<ForgeExercise[]>([]);
  const [query, setQuery] = useState(''); const [muscle, setMuscle] = useState(''); const [equipment, setEquipment] = useState('');
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [pendingDelete, setPendingDelete] = useState<ForgeExercise | null>(null);
  useEffect(() => { getForgeExercises().then(setExercises).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Übungen konnten nicht geladen werden.')).finally(() => setLoading(false)); }, []);
  const muscles = useMemo(() => [...new Set(exercises.map((item) => item.primary_muscle_group))].sort(), [exercises]);
  const filtered = useMemo(() => { const q = query.toLocaleLowerCase('de-DE').trim(); return exercises.filter((item) => (!q || `${item.name} ${item.primary_muscle_group} ${equipmentLabel[item.equipment]}`.toLocaleLowerCase('de-DE').includes(q)) && (!muscle || item.primary_muscle_group === muscle) && (!equipment || item.equipment === equipment)); }, [equipment, exercises, muscle, query]);
  const remove = async () => { if (!pendingDelete) return; try { await deleteForgeExercise(pendingDelete.id); setExercises((current) => current.filter((item) => item.id !== pendingDelete.id)); setPendingDelete(null); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : 'Übung kann nicht gelöscht werden, solange sie verwendet wird.'); } };
  if (loading) return <div className="flex justify-center py-24"><Loader2 className="animate-spin" style={{ color: SAND }} /></div>;
  return <div className="space-y-4 forge-anim"><header className="flex items-start gap-3"><button onClick={() => navigate('/forge')} className="tap mt-1 flex h-9 w-9 items-center justify-center rounded-full" aria-label="Zurück zum Forge-Plan" style={{ color: SAND, background: 'rgba(232,197,138,0.08)' }}><ArrowLeft size={18} /></button><div className="min-w-0 flex-1"><p className="text-[10px] uppercase tracking-[0.18em]" style={{ color: SAND }}>Forge Library</p><h1 className="mt-1 text-[25px] font-semibold" style={{ color: TEXT }}>Übungsbibliothek</h1><p className="mt-1 text-[11px]" style={{ color: DIM }}>{exercises.length} Übungen · zentral gepflegt</p></div></header>
    {error && <div className="rounded-2xl px-4 py-3 text-[12px]" style={{ color: '#fca5a5', background: 'rgba(248,113,113,0.1)' }}>{error}</div>}
    <div className="grid grid-cols-2 gap-2"><button onClick={() => navigate('/forge/exercises/new')} className="btn-forge flex items-center justify-center gap-2"><Plus size={15} />Neue Übung</button><button onClick={() => navigate('/forge/machine-profiles')} className="card-forge tap flex items-center justify-center gap-2 text-[11px] font-medium" style={{ color: SAND }}><Settings2 size={15} />Maschinenprofile</button></div>
    <label className="input-forge flex items-center gap-2"><Search size={15} style={{ color: DIM }} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent text-[12px] outline-none" placeholder="Übung suchen" /></label>
    <div className="grid grid-cols-2 gap-2"><select value={muscle} onChange={(event) => setMuscle(event.target.value)} className="input-forge text-[11px]"><option value="">Alle Muskeln</option>{muscles.map((item) => <option key={item}>{item}</option>)}</select><select value={equipment} onChange={(event) => setEquipment(event.target.value)} className="input-forge text-[11px]"><option value="">Alle Geräte</option>{[...new Set(exercises.map((item) => item.equipment))].map((item) => <option key={item} value={item}>{equipmentLabel[item]}</option>)}</select></div>
    <section className="space-y-2">{filtered.map((exercise) => <article key={exercise.id} className="card-forge flex items-center gap-3 p-4"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl" style={{ color: SAND, background: 'rgba(232,197,138,0.1)' }}><Dumbbell size={18} /></div><button onClick={() => navigate(`/forge/exercises/${exercise.id}/history`)} className="tap min-w-0 flex-1 text-left"><h2 className="truncate text-[13px] font-medium" style={{ color: TEXT }}>{exercise.name}</h2><p className="mt-0.5 truncate text-[10px]" style={{ color: DIM }}>{exercise.primary_muscle_group} · {equipmentLabel[exercise.equipment]}</p>{exercise.machine_profiles.length > 0 && <p className="mt-1 truncate text-[9px]" style={{ color: SAND }}>{exercise.machine_profiles.map((profile) => profile.name).join(' · ')}</p>}</button><button onClick={() => navigate(`/forge/exercises/${exercise.id}/history`)} className="tap p-1" aria-label={`${exercise.name} Verlauf`} style={{ color: SAND }}><History size={15} /></button><button onClick={() => navigate(`/forge/exercises/${exercise.id}/edit`)} className="tap p-1" aria-label={`${exercise.name} bearbeiten`} style={{ color: SAND }}><Pencil size={15} /></button><button onClick={() => setPendingDelete(exercise)} className="tap p-1" aria-label={`${exercise.name} löschen`} style={{ color: DIM }}><Trash2 size={15} /></button></article>)}{!filtered.length && <div className="card-forge p-7 text-center"><Dumbbell className="mx-auto" size={22} style={{ color: SAND }} /><p className="mt-2 text-[12px]" style={{ color: DIM }}>Keine passende Übung gefunden.</p><button onClick={() => navigate('/forge/exercises/new')} className="tap mt-3 text-[11px]" style={{ color: SAND }}>Neue Übung anlegen <ChevronRight size={13} className="inline" /></button></div>}</section>
    <ConfirmDialog open={Boolean(pendingDelete)} destructive title="Übung löschen?" description={pendingDelete ? `„${pendingDelete.name}“ wird dauerhaft entfernt. Verwendete Übungen können nicht gelöscht werden.` : ''} confirmLabel="Übung löschen" onCancel={() => setPendingDelete(null)} onConfirm={() => void remove()} />
  </div>;
}
