import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ChevronRight, Clock3, History, Loader2, Trash2 } from 'lucide-react';
import { deleteForgeSession, listForgeSessions } from '../api/api';
import type { ForgeSessionSummary } from '../api/api';
import ConfirmDialog from './ConfirmDialog';
const SAND = '#e8c58a'; const TEXT = '#f2ece0'; const DIM = 'rgba(242,236,226,0.48)';
const PAGE = 50;
export default function ForgeHistoryPage() {
  const navigate = useNavigate(); const [sessions, setSessions] = useState<ForgeSessionSummary[]>([]); const [loading, setLoading] = useState(true); const [more, setMore] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [pendingDelete, setPendingDelete] = useState<ForgeSessionSummary | null>(null);
  useEffect(() => { listForgeSessions(PAGE).then((items) => { setSessions(items); setMore(items.length === PAGE); }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : 'Verlauf konnte nicht geladen werden.')).finally(() => setLoading(false)); }, []);
  const loadMore = async () => { setBusy(true); try { const items = await listForgeSessions(PAGE, sessions.length); setSessions((current) => [...current, ...items]); setMore(items.length === PAGE); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : 'Weitere Einträge konnten nicht geladen werden.'); } finally { setBusy(false); } };
  const remove = async () => { if (!pendingDelete) return; setBusy(true); try { await deleteForgeSession(pendingDelete.id); setSessions((current) => current.filter((item) => item.id !== pendingDelete.id)); setPendingDelete(null); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : 'Workout konnte nicht gelöscht werden.'); } finally { setBusy(false); } };
  if (loading) return <div className="flex justify-center py-24"><Loader2 className="animate-spin" style={{ color: SAND }} /></div>;
  return <div className="space-y-4 forge-anim"><header className="flex items-start gap-3"><button onClick={() => navigate('/forge')} className="tap mt-1 flex h-9 w-9 items-center justify-center rounded-full" aria-label="Zurück zum Forge-Plan" style={{ color: SAND, background: 'rgba(232,197,138,0.08)' }}><ArrowLeft size={18} /></button><div><p className="text-[10px] uppercase tracking-[0.18em]" style={{ color: SAND }}>Forge Archiv</p><h1 className="mt-1 text-[25px] font-semibold" style={{ color: TEXT }}>Trainingsverlauf</h1><p className="mt-1 text-[11px]" style={{ color: DIM }}>{sessions.length} abgeschlossene Einheiten</p></div></header>{error && <div className="rounded-2xl px-4 py-3 text-[12px]" style={{ color: '#fca5a5', background: 'rgba(248,113,113,0.1)' }}>{error}</div>}<section className="space-y-2">{sessions.map((session) => <article key={session.id} className="card-forge flex items-center gap-3 p-4"><button onClick={() => navigate(`/forge/session/${session.id}`)} className="tap min-w-0 flex-1 text-left"><h2 className="truncate text-[14px] font-medium" style={{ color: TEXT }}>{session.name}</h2><p className="mt-1 text-[10px]" style={{ color: DIM }}>{new Date(session.completed_at).toLocaleDateString('de-DE', { day: '2-digit', month: 'short', year: 'numeric' })} · {session.completed_sets}/{session.total_sets} Sätze</p><p className="mt-1 flex items-center gap-1 text-[10px]" style={{ color: SAND }}><Clock3 size={11} />{Math.floor(session.duration_seconds / 60)} Min.</p></button><button onClick={() => setPendingDelete(session)} className="tap p-1" aria-label={`${session.name} löschen`} style={{ color: DIM }}><Trash2 size={15} /></button><ChevronRight size={16} style={{ color: SAND }} /></article>)}{!sessions.length && <div className="card-forge p-8 text-center"><History className="mx-auto" size={23} style={{ color: SAND }} /><p className="mt-3 text-[13px] font-medium" style={{ color: TEXT }}>Noch kein Verlauf</p><p className="mt-1 text-[11px]" style={{ color: DIM }}>Abgeschlossene Sessions erscheinen hier.</p></div>}{more && <button onClick={() => void loadMore()} disabled={busy} className="card-forge tap w-full p-3 text-[11px] font-medium" style={{ color: SAND }}>{busy ? 'Lädt…' : 'Weitere Workouts laden'}</button>}</section><ConfirmDialog open={Boolean(pendingDelete)} busy={busy} destructive title="Workout löschen?" description={pendingDelete ? `„${pendingDelete.name}“ wird dauerhaft aus dem Verlauf entfernt.` : ''} confirmLabel="Workout löschen" onCancel={() => setPendingDelete(null)} onConfirm={() => void remove()} /></div>;
}
